### ISSUE TITLE
access html_context from prolog / epilog?

### ISSUE THREAD

**Issue by rabernat** [spatialaudio/nbsphinx#419]
I use jinja with sphinx as described in [this post](https://www.ericholscher.com/blog/2016/jul/25/integrating-jinja-rst-sphinx/) to generate some content from yaml data files.

I would like to access the `html_context` data from the nbsphinx prolog / epilog. In normal rst, I can write code like:

```
{% set repo = repos['reponame'] %}
```

where `repos` is defined in my conf.py:
```
html_context = {
    'repos': repo_data
}
```

However, if I put something like this in `nbsphinx_prolog`, I get the following build error:

```
Traceback (most recent call last):
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/io.py", line 316, in read_doc
    pub.publish()
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/io.py", line 130, in read
    self.parse()
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/nbsphinx.py", line 923, in parse
    prolog = exporter.environment.from_string(
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 2, in top-level template code
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'repos' is undefined
```

Is there a way to expose the `html_context` variables to jinja when it is parsing the prolog / epilog?

p.s. Thanks for this amazing, incredibly useful tool

**Comment by mgeier** [comment]
You can use

    {% set repo = env.config.html_context.repos['reponame'] %}

or, if you prefer:

    {% set repo = env.config.html_context.repos.reponame %}

I could add the `html_context` directly to the Jinja environment, but I don't think that makes sense, because the prolog/epilog are not HTML specific.

I could add `config`, though ... would that make sense?

**Comment by rabernat** [comment]
Thanks for the tip. Works perfectly!

Would you be interested in a PR to mention this trick in the documentation?

**Comment by mgeier** [comment]
> Would you be interested in a PR to mention this trick in the documentation?

Yes, sure!
