### ISSUE TITLE
Error on running 'python -m pip install -r theme_comparison/theme_requirements.txt' 

### ISSUE THREAD

**Issue by 1kastner** [spatialaudio/nbsphinx#634]
When I tried to install all themes as advised at https://github.com/spatialaudio/nbsphinx/blob/efd08d8f777dcf7f435625b4a5726e240b5e2937/CONTRIBUTING.rst#building-themes, I encountered several errors. To be more precise, two errors repeatedly occured, i.e.:
- `error in jupyter-sphinx-theme setup command: use_2to3 is invalid.`
- `ModuleNotFoundError: No module named 'recommonmark'`

The full output was this:
```
(venv) PS NBSPHINX_DIR> python -m pip install -r theme_comparison/theme_requirements.txt
Collecting git+https://github.com/shiftlab/pytorch_sphinx_theme.git (from -r theme_comparison/theme_requirements.txt (line 5))
  Cloning https://github.com/shiftlab/pytorch_sphinx_theme.git to MY_APP_DATA\local\temp\pip-req-build-80e_az5p
  Running command git clone --filter=blob:none -q https://github.com/shiftlab/pytorch_sphinx_theme.git 'MY_APP_DATA\Local\Temp\pip-req-build-80e_az5p'
  Resolved https://github.com/shiftlab/pytorch_sphinx_theme.git to commit e35354d32dd71ac14b87dffa1ef28f8c73b651e7
  Preparing metadata (setup.py) ... done
Collecting astropy-sphinx-theme
  Downloading astropy_sphinx_theme-1.1-py2.py3-none-any.whl (31 kB)
Collecting cloud_sptheme
  Downloading cloud_sptheme-1.10.1.post20200504175005-py2.py3-none-any.whl (91 kB)
     |████████████████████████████████| 91 kB 1.1 MB/s
Collecting dask-sphinx-theme
  Downloading dask_sphinx_theme-2.0.1-py3-none-any.whl (25 kB)
Collecting furo
  Downloading furo-2022.1.2-py3-none-any.whl (286 kB)
     |████████████████████████████████| 286 kB ...
Collecting guzzle_sphinx_theme
  Downloading guzzle_sphinx_theme-0.7.11.tar.gz (2.5 MB)
     |████████████████████████████████| 2.5 MB 6.8 MB/s
  Preparing metadata (setup.py) ... done
Collecting insipid-sphinx-theme
  Downloading insipid_sphinx_theme-0.2.9-py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB ...
Collecting jupyter-sphinx-theme
  Downloading jupyter-sphinx-theme-0.0.6.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB ...
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'NBSPHINX_DIR\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'MY_APP_DATA\\Local\\Temp\\pip-install-pqwb9clk\\jupyter-sphinx-theme_e5f0ad5922d046ca9ce5bd6eac59602b\\setup.py'"'"'; __file__='"'"'MY_APP_DATA\\Local\\Temp\\pip-install-pqwb9clk\\jupyter-sphinx-theme_e5f0ad5922d046ca9ce5bd6eac59602b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'MY_APP_DATA\Local\Temp\pip-pip-egg-info-m8nr0rry'
       cwd: MY_APP_DATA\Local\Temp\pip-install-pqwb9clk\jupyter-sphinx-theme_e5f0ad5922d046ca9ce5bd6eac59602b\
  Complete output (1 lines):
  error in jupyter-sphinx-theme setup command: use_2to3 is invalid.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/1d/c1/e32fd73e7bcb9f5ee1e6af2d190faba5e74db42317a4b8a7bca83502f83c/jupyter-sphinx-theme-0.0.6.tar.gz#sha256=bd8da9cb3d00793b1479a6397d1eec524d7f55acfb20d8097afa69ee7f37bd90 (from https://pypi.org/simple/jupyter-sphinx-theme/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading jupyter-sphinx-theme-0.0.5.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB ...
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'NBSPHINX_DIR\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'MY_APP_DATA\\Local\\Temp\\pip-install-pqwb9clk\\jupyter-sphinx-theme_faaf57596ae644828dd015b5be490bf6\\setup.py'"'"'; __file__='"'"'MY_APP_DATA\\Local\\Temp\\pip-install-pqwb9clk\\jupyter-sphinx-theme_faaf57596ae644828dd015b5be490bf6\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'MY_APP_DATA\Local\Temp\pip-pip-egg-info-lkguwbaw'
       cwd: MY_APP_DATA\Local\Temp\pip-install-pqwb9clk\jupyter-sphinx-theme_faaf57596ae644828dd015b5be490bf6\
  Complete output (1 lines):
  error in jupyter-sphinx-theme setup command: use_2to3 is invalid.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/28/64/79d93c0cafccd51c2dd5d975642f6c4ceb20c4bd0a43b3136ca4a4dd37cd/jupyter-sphinx-theme-0.0.5.tar.gz#sha256=9ede2cc085af8cfdc0865de52ad59c21f3424d0b507393b7c1d7a4db70a1a4c3 (from https://pypi.org/simple/jupyter-sphinx-theme/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading jupyter-sphinx-theme-0.0.4.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB ...
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'NBSPHINX_DIR\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'MY_APP_DATA\\Local\\Temp\\pip-install-pqwb9clk\\jupyter-sphinx-theme_672d46936ea34042b01f8a96fd162db8\\setup.py'"'"'; __file__='"'"'MY_APP_DATA\\Local\\Temp\\pip-install-pqwb9clk\\jupyter-sphinx-theme_672d46936ea34042b01f8a96fd162db8\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'MY_APP_DATA\Local\Temp\pip-pip-egg-info-9mlrjr36'
       cwd: MY_APP_DATA\Local\Temp\pip-install-pqwb9clk\jupyter-sphinx-theme_672d46936ea34042b01f8a96fd162db8\
  Complete output (1 lines):
  error in jupyter-sphinx-theme setup command: use_2to3 is invalid.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7a/5f/93cf91d1fb2c69e2f785602215bca0b63e0c75eb92294ab561bf63b3baef/jupyter-sphinx-theme-0.0.4.tar.gz#sha256=c61b23b61daa1cc01b9d40097b40ebc8173112a4810483ad8c501bf1d70d79d5 (from https://pypi.org/simple/jupyter-sphinx-theme/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading jupyter-sphinx-theme-0.0.3.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 6.4 MB/s
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'NBSPHINX_DIR\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'MY_APP_DATA\\Local\\Temp\\pip-install-pqwb9clk\\jupyter-sphinx-theme_528d453ee36a4370af822f9ce5e1ffe2\\setup.py'"'"'; __file__='"'"'MY_APP_DATA\\Local\\Temp\\pip-install-pqwb9clk\\jupyter-sphinx-theme_528d453ee36a4370af822f9ce5e1ffe2\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'MY_APP_DATA\Local\Temp\pip-pip-egg-info-fq42s9pc'
       cwd: MY_APP_DATA\Local\Temp\pip-install-pqwb9clk\jupyter-sphinx-theme_528d453ee36a4370af822f9ce5e1ffe2\
  Complete output (1 lines):
  error in jupyter-sphinx-theme setup command: use_2to3 is invalid.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/52/74/ed9bcea8d1eac8f9a16652ecda39fc9d552b64239aaa49658cae61d40b01/jupyter-sphinx-theme-0.0.3.tar.gz#sha256=fc89e5e1ea2cb96d078848b0a4bf4d92d1ba02744d933c2f3a1651b2b0bd4611 (from https://pypi.org/simple/jupyter-sphinx-theme/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading jupyter-sphinx-theme-0.0.2.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 6.4 MB/s
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'NBSPHINX_DIR\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'MY_APP_DATA\\Local\\Temp\\pip-install-pqwb9clk\\jupyter-sphinx-theme_50bc38828a6048188e27500ce1ece760\\setup.py'"'"'; __file__='"'"'MY_APP_DATA\\Local\\Temp\\pip-install-pqwb9clk\\jupyter-sphinx-theme_50bc38828a6048188e27500ce1ece760\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'MY_APP_DATA\Local\Temp\pip-pip-egg-info-22w5ovah'
       cwd: MY_APP_DATA\Local\Temp\pip-install-pqwb9clk\jupyter-sphinx-theme_50bc38828a6048188e27500ce1ece760\
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "MY_APP_DATA\Local\Temp\pip-install-pqwb9clk\jupyter-sphinx-theme_50bc38828a6048188e27500ce1ece760\setup.py", line 5, in <module>
      from jupyter_sphinx_theme import __version__
    File "MY_APP_DATA\Local\Temp\pip-install-pqwb9clk\jupyter-sphinx-theme_50bc38828a6048188e27500ce1ece760\jupyter_sphinx_theme\__init__.py", line 5, in <module>
      from recommonmark.parser import CommonMarkParser
  ModuleNotFoundError: No module named 'recommonmark'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c2/ee/8a6038bbf4c2db442cc28a41e68b8dac8d9fe96d16cc97374290845c7a2c/jupyter-sphinx-theme-0.0.2.tar.gz#sha256=c7f81a52ad3ff5c2d85da39263507621170f8c822f443edf31be9f66272c6928 (from https://pypi.org/simple/jupyter-sphinx-theme/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading jupyter-sphinx-theme-0.0.1.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 6.8 MB/s
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'NBSPHINX_DIR\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'MY_APP_DATA\\Local\\Temp\\pip-install-pqwb9clk\\jupyter-sphinx-theme_df19b3b63eba431cad9fe50fd282bbbe\\setup.py'"'"'; __file__='"'"'MY_APP_DATA\\Local\\Temp\\pip-install-pqwb9clk\\jupyter-sphinx-theme_df19b3b63eba431cad9fe50fd282bbbe\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'MY_APP_DATA\Local\Temp\pip-pip-egg-info-v4dk8zhk'
       cwd: MY_APP_DATA\Local\Temp\pip-install-pqwb9clk\jupyter-sphinx-theme_df19b3b63eba431cad9fe50fd282bbbe\
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "MY_APP_DATA\Local\Temp\pip-install-pqwb9clk\jupyter-sphinx-theme_df19b3b63eba431cad9fe50fd282bbbe\setup.py", line 5, in <module>
      from jupyter_sphinx_theme import __version__
    File "MY_APP_DATA\Local\Temp\pip-install-pqwb9clk\jupyter-sphinx-theme_df19b3b63eba431cad9fe50fd282bbbe\jupyter_sphinx_theme\__init__.py", line 5, in <module>
      from recommonmark.parser import CommonMarkParser
  ModuleNotFoundError: No module named 'recommonmark'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ab/c9/53d7256f8ac15a71c485ee6c973c2f495e1d4a9f567e823dfd8eb8ab7c5f/jupyter-sphinx-theme-0.0.1.tar.gz#sha256=2bb43610c8f13b22ebd54bc14b6bec18abea577ec473be92900293ca02edceaf (from https://pypi.org/simple/jupyter-sphinx-theme/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement jupyter-sphinx-theme (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6)
ERROR: No matching distribution found for jupyter-sphinx-theme
(venv) PS NBSPHINX_DIR>
```

I would like to get some guidance how these errors can be resolved appropriately so that the output looks as intended by the delevopers of this repository.

**Comment by mgeier** [comment]
Yeah, the jupyter-sphinx-theme seems to be broken.

I've removed it from the documentation in #619, but I've forgotten to delete the branch in the repo.

I have just deleted the branch, now it should work!

**Comment by 1kastner** [comment]
Now the installation process finished successfully, thanks!
