### ISSUE TITLE
0.9.2: documentation build fails

### ISSUE THREAD

**Issue by kloczek** [spatialaudio/nbsphinx#757]
```console
+ /usr/bin/sphinx-build -n -T -b man doc build/sphinx/man
Running Sphinx v7.0.1
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
making output directory... done
[autosummary] generating autosummary for: code_links.rst, devel/design.rst, devel/improving_markdown.rst, devel/make_release.rst, devel/sphinx_example_project.rst, index.rst, introduction.rst, markdown_base.rst, mpl_interactive.rst, nbplots.rst, scripts.rst, worked_example.rst
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 12 added, 0 changed, 0 removed
reading sources... [  8%] code_links
reading sources... [ 16%] devel/design
reading sources... [ 25%] devel/improving_markdown
reading sources... [ 33%] devel/make_release
reading sources... [ 41%] devel/sphinx_example_project
reading sources... [ 50%] index
reading sources... [ 58%] introduction
reading sources... [ 66%] markdown_base
reading sources... [ 75%] mpl_interactive
reading sources... [ 83%] nbplots
reading sources... [ 91%] scripts
reading sources... [100%] worked_example

/home/tkloczko/rpmbuild/BUILD/nb2plots-0.6.1/doc/index.rst:37: WARNING: toctree contains reference to nonexisting document 'converted_example'
/home/tkloczko/rpmbuild/BUILD/nb2plots-0.6.1/doc/index.rst:37: WARNING: toctree contains reference to nonexisting document 'converted_plus_notebooks'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-nb2plots.3 { introduction worked_example scripts nbplots mpl_interactive code_links markdown_base devel/improving_markdown devel/sphinx_example_project devel/make_release devel/design } /home/tkloczko/rpmbuild/BUILD/nb2plots-0.6.1/doc/worked_example.rst:15: WARNING: unknown document: 'converted_example'
/home/tkloczko/rpmbuild/BUILD/nb2plots-0.6.1/doc/worked_example.rst:53: WARNING: unknown document: 'converted_plus_notebooks'
/home/tkloczko/rpmbuild/BUILD/nb2plots-0.6.1/nb2plots/nbplots.py:docstring of nb2plots.nbplots:84: WARNING: py:class reference target not found: NBPlotFlags
done

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/tkloczko/rpmbuild/BUILD/nb2plots-0.6.1/nb2plots/runroles.py", line 309, in write_runfiles
    NAME2ROLE[code_type].write_queue(queue, app)
  File "/home/tkloczko/rpmbuild/BUILD/nb2plots-0.6.1/nb2plots/runroles.py", line 104, in write_queue
    self.write(node, app)
  File "/home/tkloczko/rpmbuild/BUILD/nb2plots-0.6.1/nb2plots/runroles.py", line 118, in write
    built = self.get_built(node, app)
  File "/home/tkloczko/rpmbuild/BUILD/nb2plots-0.6.1/nb2plots/runroles.py", line 142, in get_built
    own_params[code_type] = self._build(node, app)
  File "/home/tkloczko/rpmbuild/BUILD/nb2plots-0.6.1/nb2plots/runroles.py", line 148, in _build
    builder = self.builder_class(app)
  File "/home/tkloczko/rpmbuild/BUILD/nb2plots-0.6.1/nb2plots/sphinx2foos.py", line 18, in __init__
    super(MarkdownBuilder, self).__init__(app)
TypeError: __init__() missing 1 required positional argument: 'env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 353, in build
    self.events.emit('build-finished', None)
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function write_runfiles at 0x7f9566d78a60> for event 'build-finished' threw an exception (exception: __init__() missing 1 required positional argument: 'env')

Extension error (nb2plots.runroles):
Handler <function write_runfiles at 0x7f9566d78a60> for event 'build-finished' threw an exception (exception: __init__() missing 1 required positional argument: 'env')
```

**Comment by kloczek** [comment]
Sorry mistake.
I've alredy reported that.
